"use strict";
const SITE="https://calm-down-quotes.github.io/motivation/";
const STORAGE={saved:"mq_saved_v3",theme:"mq_theme_v3"};
const NEEDS={focus:["Focus","Cut through the noise."],discipline:["Discipline","Do what matters consistently."],confidence:["Confidence","Trust what you are capable of."],courage:["Courage","Move while uncertainty is still there."],momentum:["Momentum","Get moving again."],resilience:["Resilience","Keep going without grinding yourself down."]};
const FALLBACK={id:"fallback",text:"You do not need the perfect moment. You need one useful move.",note:"Progress can begin before everything feels settled.",action:"Choose the smallest useful action available and complete it.",need:"momentum"};
let quotes=[FALLBACK],current=FALLBACK,lastFocus=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const el={quote:$("#quote"),note:$("#note"),action:$("#action"),wrap:$("#quote-wrap"),save:$("#save"),count:$("#count"),saved:$("#saved-list"),needs:$("#needs"),layer:$("#share-layer"),shareQuote:$("#share-quote"),menu:$(".menu"),nav:$(".header nav")};
function track(name,params={}){try{if(typeof window.gtag==="function")window.gtag("event",name,{page_id:"motivation",...params})}catch{}}
function read(key,fallback){try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}}
function write(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function savedIds(){return read(STORAGE.saved,[]).filter(x=>typeof x==="string")}
function isSaved(id){return savedIds().includes(id)}
function syncSave(){const saved=isSaved(current.id);el.save.textContent=saved?"Saved":"Save this one";el.save.setAttribute("aria-pressed",String(saved));el.count.textContent=String(savedIds().length)}
function setQuery(id){try{const u=new URL(location.href);u.searchParams.set("q",id);history.replaceState(null,"",u)}catch{}}
function render(q,animate=true){current=q||FALLBACK;const update=()=>{el.quote.textContent=current.text;el.note.textContent=current.note;el.action.textContent=current.action;syncSave();setQuery(current.id);track("quote_view",{quote_id:current.id,need:current.need})};if(animate&&!matchMedia("(prefers-reduced-motion: reduce)").matches){el.wrap.classList.add("changing");setTimeout(()=>{update();el.wrap.classList.remove("changing")},180)}else update()}
function choose(pool=quotes){const list=pool.length?pool:quotes;if(list.length===1)return list[0];let next=current;for(let i=0;i<8&&next.id===current.id;i++)next=list[Math.floor(Math.random()*list.length)];return next}
function showRandom(need=null){const pool=need?quotes.filter(q=>q.need===need):quotes;render(choose(pool));showView("home");track("quote_generated",{need:need||"any"})}
function showView(id){$$('.view').forEach(v=>v.classList.toggle("active",v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle("active",b.dataset.view===id));el.nav.classList.remove("open");el.menu.setAttribute("aria-expanded","false");if(id==="saved")renderSaved();if(id!=="home")history.replaceState(null,"",location.pathname)}
function renderNeeds(){el.needs.replaceChildren(...Object.entries(NEEDS).map(([key,[title,desc]])=>{const b=document.createElement("button");const strong=document.createElement("strong");strong.textContent=title;const span=document.createElement("span");span.textContent=desc;b.append(strong,span);b.addEventListener("click",()=>showRandom(key));return b}))}
function toggleSave(){const ids=savedIds();const i=ids.indexOf(current.id);if(i>=0)ids.splice(i,1);else ids.unshift(current.id);write(STORAGE.saved,ids.slice(0,100));syncSave();track(i>=0?"quote_unsaved":"quote_saved",{quote_id:current.id})}
function renderSaved(){const ids=savedIds();el.saved.replaceChildren();if(!ids.length){const p=document.createElement("p");p.className="empty";p.textContent="Nothing saved yet. Save a quote and it will stay here on this device.";el.saved.append(p);return}ids.forEach(id=>{const q=quotes.find(x=>x.id===id);if(!q)return;const card=document.createElement("article");card.className="saved-card";const left=document.createElement("div");const text=document.createElement("p");text.textContent=q.text;const small=document.createElement("small");small.textContent=q.action;left.append(text,small);const remove=document.createElement("button");remove.type="button";remove.textContent="Remove";remove.addEventListener("click",()=>{write(STORAGE.saved,savedIds().filter(x=>x!==id));syncSave();renderSaved()});card.append(left,remove);el.saved.append(card)})}
function applyTheme(theme){const safe=["light","road","ember"].includes(theme)?theme:"light";document.body.className=`theme-${safe}`;$$('[data-theme]').forEach(b=>b.classList.toggle("selected",b.dataset.theme===safe));write(STORAGE.theme,safe);track("theme_change",{theme:safe})}
function shareUrl(){return `${SITE}?q=${encodeURIComponent(current.id)}`}
function shareText(){return `“${current.text}”\n\n${current.note}\n\nNext move: ${current.action}\n\n${shareUrl()}`}
function openShare(){lastFocus=document.activeElement;el.shareQuote.textContent=`“${current.text}”`;el.layer.hidden=false;$("#close-share").focus();document.body.style.overflow="hidden"}
function closeShare(){el.layer.hidden=true;document.body.style.overflow="";if(lastFocus?.focus)lastFocus.focus()}
function popup(url){window.open(url,"_blank","noopener,noreferrer")}
async function copyShare(){try{await navigator.clipboard.writeText(shareText());$("#copy").textContent="Copied";setTimeout(()=>$("#copy").textContent="Copy quote and link",1300)}catch{}}
function wrapText(ctx,text,x,y,max,line){const words=text.split(/\s+/);let row="",rows=[];for(const w of words){const test=row?`${row} ${w}`:w;if(ctx.measureText(test).width>max&&row){rows.push(row);row=w}else row=test}if(row)rows.push(row);const start=y-(rows.length-1)*line/2;rows.forEach((r,i)=>ctx.fillText(r,x,start+i*line))}
function makeImage(){const c=document.createElement("canvas");c.width=1080;c.height=1350;const x=c.getContext("2d");const theme=document.body.className.includes("ember")?["#2d170f","#7f3e28","#fff3e8"]:document.body.className.includes("road")?["#e9dfcf","#98a58b","#293126"]:["#fff3e4","#d99a6a","#37251b"];const g=x.createLinearGradient(0,0,1080,1350);g.addColorStop(0,theme[0]);g.addColorStop(1,theme[1]);x.fillStyle=g;x.fillRect(0,0,1080,1350);x.fillStyle=theme[2];x.textAlign="center";x.font="34px Georgia";x.globalAlpha=.72;x.fillText("MOTIVATIONAL QUOTES",540,130);x.globalAlpha=1;x.font="66px Georgia";wrapText(x,current.text,540,430,830,82);x.font="30px Arial";x.globalAlpha=.78;wrapText(x,current.action,540,980,760,44);x.globalAlpha=.6;x.font="24px Arial";x.fillText("calm-down-quotes.github.io/motivation",540,1220);return c}
async function shareImage(){const canvas=makeImage();const blob=await new Promise(r=>canvas.toBlob(r,"image/png"));if(!blob)return;const file=new File([blob],"motivational-quote.png",{type:"image/png"});try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:"Motivational Quote",text:current.text});return}}catch(e){if(e.name==="AbortError")return}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="motivational-quote.png";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function nativeShare(){try{if(navigator.share){await navigator.share({title:"Motivational Quote",text:current.text,url:shareUrl()})}else openShare()}catch(e){if(e.name!=="AbortError")openShare()}}
async function clearOldWorker(){try{if("serviceWorker" in navigator){const regs=await navigator.serviceWorker.getRegistrations();for(const reg of regs){if(reg.scope.includes("/motivational-quotes/"))await reg.unregister()}}if("caches" in window){const keys=await caches.keys();for(const key of keys){if(key.startsWith("motivational-quotes-"))await caches.delete(key)}}}catch{}}
async function load(){clearOldWorker();try{const res=await fetch("quotes.json",{cache:"no-store"});if(!res.ok)throw new Error(String(res.status));const data=await res.json();if(Array.isArray(data)&&data.length)quotes=data}catch(e){console.error("Quote library fallback in use",e)}renderNeeds();applyTheme(read(STORAGE.theme,"light"));const wanted=new URLSearchParams(location.search).get("q");const q=quotes.find(x=>x.id===wanted)||choose(quotes);render(q,false);syncSave()}
$$('[data-view]').forEach(b=>b.addEventListener("click",()=>showView(b.dataset.view)));$("#another").addEventListener("click",()=>showRandom());$("#any").addEventListener("click",()=>showRandom());el.save.addEventListener("click",toggleSave);$("#share").addEventListener("click",nativeShare);el.menu.addEventListener("click",()=>{const open=el.nav.classList.toggle("open");el.menu.setAttribute("aria-expanded",String(open))});$$('[data-theme]').forEach(b=>b.addEventListener("click",()=>applyTheme(b.dataset.theme)));$("#close-share").addEventListener("click",closeShare);el.layer.addEventListener("click",e=>{if(e.target===el.layer)closeShare()});document.addEventListener("keydown",e=>{if(e.key==="Escape"&&!el.layer.hidden)closeShare()});$("#copy").addEventListener("click",copyShare);$("#share-image").addEventListener("click",shareImage);$$('[data-share]').forEach(b=>b.addEventListener("click",()=>{const u=encodeURIComponent(shareUrl()),t=encodeURIComponent(shareText());if(b.dataset.share==="whatsapp")popup(`https://wa.me/?text=${t}`);if(b.dataset.share==="facebook")popup(`https://www.facebook.com/sharer/sharer.php?u=${u}`);if(b.dataset.share==="x")popup(`https://twitter.com/intent/tweet?text=${encodeURIComponent(current.text)}&url=${u}`);if(b.dataset.share==="email")location.href=`mailto:?subject=Motivational%20Quote&body=${t}`}));
load();