"use strict";
const FALLBACK=[{id:1,text:"You do not have to solve your whole life tonight. Just be here, for this breath.",note:"A gentle reminder",category:"Anxiety relief",feelings:["overwhelmed","anxious","grounding"],origin:"Calm Down Quotes original"}];
const LABELS={overwhelmed:"Overwhelmed",anxious:"Anxious",uncertain:"Uncertain",tired:"Tired",grounding:"Need grounding"};
const THEMES=["dawn","water","moonlight"];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let quotes=FALLBACK,current=FALLBACK[0],feeling=null,saved=safeRead("calm-saved",[]),lastFocus=null;
function safeRead(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function safeWrite(key,value){try{localStorage.setItem(key,JSON.stringify(value))}catch{}}
function defaultTheme(){const h=new Date().getHours();return h>=19||h<5?"moonlight":h<11?"dawn":"water"}
function theme(){return document.body.className.replace("theme-","")}
function setTheme(value){const t=THEMES.includes(value)?value:"water";document.body.className=`theme-${t}`;try{localStorage.setItem("calm-theme",t)}catch{}$$('[data-theme]').forEach(b=>b.classList.toggle("selected",b.dataset.theme===t));document.querySelector('meta[name="theme-color"]').content=t==="moonlight"?"#182c42":t==="dawn"?"#f4d6bd":"#a8c5c4"}
function render(){ $("#quote").textContent=current.text;$("#note").textContent=current.note;$("#save").textContent=saved.includes(current.id)?"Saved gently ✓":"Save this one";$("#count").textContent=String(saved.length)}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));$('nav').classList.remove('open');if(id==='saved')renderSaved();window.scrollTo({top:0,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
function pool(){return feeling?quotes.filter(q=>q.feelings.includes(feeling)):quotes}
function another(){const choices=pool().filter(q=>q.id!==current.id),wrap=$('#quote-wrap');wrap.classList.add('changing');setTimeout(()=>{current=choices[Math.floor(Math.random()*choices.length)]||pool()[0]||FALLBACK[0];render();wrap.classList.remove('changing')},220)}
function toggleSave(){saved=saved.includes(current.id)?saved.filter(id=>id!==current.id):[...saved,current.id];safeWrite('calm-saved',saved);render()}
function renderSaved(){const box=$('#saved-list'),items=quotes.filter(q=>saved.includes(q.id));box.innerHTML=items.length?items.map(q=>`<article class="saved-card"><p>“${escapeHTML(q.text)}”</p><button data-remove="${q.id}">Remove</button></article>`).join(''):'<p>No saved quotes yet. Gentle reminders you save will appear here.</p>';$$('[data-remove]').forEach(b=>b.onclick=()=>{saved=saved.filter(id=>id!==Number(b.dataset.remove));safeWrite('calm-saved',saved);render();renderSaved()})}
function escapeHTML(text){return text.replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function shareURL(){const u=new URL(location.origin+location.pathname);u.searchParams.set('quote',String(current.id));u.searchParams.set('atmosphere',theme());return u.href}
function shareText(){return `“${current.text}”\n\n${current.note} — Calm Down Quotes`}
function openSheet(){lastFocus=document.activeElement;$('#share-quote').textContent=`“${current.text}”`;$('#share-layer').hidden=false;$('#close-share').focus()}
function closeSheet(){$('#share-layer').hidden=true;if(lastFocus)lastFocus.focus()}
async function nativeShare(){if(navigator.share){try{await navigator.share({title:'A gentle quote for you',text:shareText(),url:shareURL()});return}catch(e){if(e.name==='AbortError')return}}openSheet()}
async function copyShare(){try{await navigator.clipboard.writeText(`${shareText()}\n\n${shareURL()}`);$('#copy').textContent='Copied gently ✓';setTimeout(()=>$('#copy').textContent='Copy quote and link',1600)}catch{$('#copy').textContent='Select and copy the quote above'}}
function appShare(app){const u=encodeURIComponent(shareURL()),t=encodeURIComponent(shareText()),dest={whatsapp:`https://wa.me/?text=${t}%0A%0A${u}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${u}`,x:`https://twitter.com/intent/tweet?text=${t}&url=${u}`,email:`mailto:?subject=${encodeURIComponent('A gentle quote for you')}&body=${t}%0A%0A${u}`};open(dest[app],'_blank','noopener,noreferrer')}
async function shareImage(){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d'),pal=theme()==='moonlight'?['#0b192b','#e9edf2','#a9bdce']:theme()==='dawn'?['#f7eee2','#173a30','#7a927c']:['#dce8e5','#24363d','#799f98'];c.fillStyle=pal[0];c.fillRect(0,0,1080,1350);const g=c.createRadialGradient(790,240,20,760,260,700);g.addColorStop(0,theme()==='dawn'?'#f6c8aa88':theme()==='moonlight'?'#91abc555':'#f7faf788');g.addColorStop(1,'transparent');c.fillStyle=g;c.fillRect(0,0,1080,1350);c.fillStyle=pal[1];c.textAlign='center';c.font='64px Georgia';wrapCanvas(c,current.text,540,470,850,82);c.fillStyle=pal[2];c.font='30px Arial';c.fillText(current.note,540,1000);c.font='26px Arial';c.fillText('Calm Down Quotes',540,1215);const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=new File([blob],`calm-down-quote-${current.id}.png`,{type:'image/png'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'A gentle quote for you',text:shareText(),files:[file]});return}catch(e){if(e.name==='AbortError')return}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
function wrapCanvas(c,text,x,y,max,line){const words=text.split(' '),lines=[];let row='';for(const word of words){const test=row?`${row} ${word}`:word;if(c.measureText(test).width>max&&row){lines.push(row);row=word}else row=test}if(row)lines.push(row);lines.forEach((l,i)=>c.fillText(l,x,y+i*line))}
function wire(){ $('#another').onclick=another;$('#save').onclick=toggleSave;$('#share').onclick=nativeShare;$('#copy').onclick=copyShare;$('#share-image').onclick=shareImage;$('#close-share').onclick=closeSheet;$('#share-layer').onclick=e=>{if(e.target.id==='share-layer')closeSheet()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#share-layer').hidden)closeSheet()});$$('[data-share]').forEach(b=>b.onclick=()=>appShare(b.dataset.share));$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$('.menu').onclick=()=>{const n=$('nav'),open=n.classList.toggle('open');$('.menu').setAttribute('aria-expanded',String(open))};$$('[data-theme]').forEach(b=>b.onclick=()=>setTheme(b.dataset.theme));$('#any').onclick=()=>{feeling=null;another();showView('home')};Object.entries(LABELS).forEach(([key,label])=>{const b=document.createElement('button');b.textContent=label;b.onclick=()=>{feeling=key;const choices=quotes.filter(q=>q.feelings.includes(key));current=choices[Math.floor(Math.random()*choices.length)]||FALLBACK[0];render();showView('home')};$('#feelings').append(b)})}
async function init(){try{const res=await fetch('quotes-safe.json',{cache:'no-cache'});if(!res.ok)throw Error('quote library unavailable');const data=await res.json();if(!Array.isArray(data)||!data.length)throw Error('invalid quote library');quotes=data}catch(e){console.warn(e.message);quotes=FALLBACK}const params=new URLSearchParams(location.search),shared=quotes.find(q=>q.id===Number(params.get('quote')));current=shared||quotes[new Date().getUTCDate()%quotes.length]||FALLBACK[0];setTheme(THEMES.includes(params.get('atmosphere'))?params.get('atmosphere'):(localStorage.getItem('calm-theme')||defaultTheme()));wire();render();if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}))}
init();
